# Collaborators (including web sites where you got help: (enter none if you didn't need help)
#  

name = input("What is your name?")
color = input("what is yoru favorite color?")
animal = input("What is your favorite animal?")
adjective = input("what is your favoirte adjective?")
adjective2 = input("what is your second favoirte adjective?")
food = input("What is your favoirte food?")
place = input("what is your favorite place to go in the world?")
job = input("What is your dream job?")
hobby = input("what is your # 1 hobby?")
print("...................................................")
print(name + " Bizzare Adventure")
print("Once upon a time long long ago, the great hero " + name + " decided to take a trip to the far far land of " + place + ", in order to take down their greatest enemy, the " + job, food + ".")
print(name + " manifested his soul energy into his ultimate sidekick " + adjective + adjective2 + color + animal + " and using his " + hobby + " attack to destroy " + job, food + " once and for all saving the " + adjective, place + ".")
print("THE END")